# Generated by Django 4.0.6 on 2023-02-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('small_description', models.TextField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
            ],
        ),
    ]
